version: "3"
services:
  xbeach-orchestrator:
    image: deltares/xbeach-mi
    depends_on:
      - stat
      - instat
    volumes:
      - ./orchestrator/:/data
  stat:
    image: deltares/xbeach
    environment:
      - PORT=53606
    volumes:
      - ./stat/:/data
  instat:
    image: deltares/xbeach
    environment:
      - PORT=53609
    volumes:
      - ./instat/:/data
